#!/bin/bash
#  Setup versions for image components
#  This script should be sourced by the other scripts
SYSLINUX=syslinux-6.03
BUILDROOT=git@github.com:buildroot/buildroot.git
BUILDROOT_TAG=2019.02.6
